apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fdm8kxr0d-nodejs 
  janus-idp.io/tekton: fdm8kxr0d-nodejs
  backstage.io/kubernetes-id: fdm8kxr0d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fdm8kxr0d-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  